name: Monthly Portfolio Data Update

on:
  schedule:
    # Run at 8:15 AM EST on the 1st of every month
    - cron: '15 13 1 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  monthly-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure secrets
      run: |
        echo "${{ secrets.SECRETS_TOML }}" > secrets.toml
      env:
        TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
      
    - name: Run monthly workflow
      run: python monthly_automation.py --now
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monthly-automation-logs
        path: monthly_automation.log